[redshift]
; Нейтральная температура цвета - 6500K. Использование этой величины
; не изменит температуру цвета дисплея. Установка температуры цвета
; больше этого значения приведет к более синему цвету экрана,
; установка меньшего значения - к более красному оттенку.
; Значения по умолчанию:
;  Температура цвета днем: 5500K
;  Температура цвета ночью: 3500K
temp-day=5000
temp-night=2700
transition=1
brightness-day=0.9
brightness-night=0.6
location-provider=geoclue2
adjustment-method=randr
