#! /bin/sh

nitrogen --restore
killall picom; (sleep 1; picom) &
~/.config/polybar/launch.sh
killall redshift-gtk; (redshift-gtk) &
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle
killall sxhkd; sxhkd &
wmname LG3D

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          1
bspc config window_gap            5

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# xprop | grep WM_CLASS
bspc rule -a firefox desktop=^1 follow=no
bspc rule -a Steam desktop=^6 follow=no
bspc rule -a TelegramDesktop desktop=^4 
bspc rule -a VK desktop=^4
bspc rule -a discord desktop=^5 follow=no
bspc rule -a Pcmanfm state=floating rectangle=800x600
bspc rule -a CounterStrike desktop=^7
bspc rule -a Pavucontrol state=floating rectangle=800x600
bspc rule -a Nitrogen state=floating rectangle=400x300
bspc rule -a jetbrains-pycharm desktop=^3
bspc rule -a jetbrains-clion desktop=^3
bspc rule -a jetbrains-webstorm desktop=^3
bspc rule -a ark state=floating rectangle=800x600
